"""Drop tables

Revision ID: 0c6453b1b71f
Revises: 1ccb06999ac9
Create Date: 2023-06-01 17:04:08.028116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6453b1b71f'
down_revision = '1ccb06999ac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
