"""create table v4

Revision ID: 09168501e8bd
Revises: 650035e7a17c
Create Date: 2023-06-15 09:00:39.969080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09168501e8bd'
down_revision = '650035e7a17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('properties', 'createdat')
    op.drop_column('properties', 'updatedat')
    op.add_column('rental_history', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rental_history', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('rental_history', 'createdat')
    op.drop_column('rental_history', 'updatedat')
    op.add_column('transaction_history', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transaction_history', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('transaction_history', 'createdat')
    op.drop_column('transaction_history', 'updatedat')
    op.add_column('users', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'createdat')
    op.drop_column('users', 'updatedat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updatedat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('createdat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.add_column('transaction_history', sa.Column('updatedat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('transaction_history', sa.Column('createdat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('transaction_history', 'updatedAt')
    op.drop_column('transaction_history', 'createdAt')
    op.add_column('rental_history', sa.Column('updatedat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('rental_history', sa.Column('createdat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('rental_history', 'updatedAt')
    op.drop_column('rental_history', 'createdAt')
    op.add_column('properties', sa.Column('updatedat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('createdat', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('properties', 'updatedAt')
    op.drop_column('properties', 'createdAt')
    # ### end Alembic commands ###
