"""create table

Revision ID: 1dadc39e1615
Revises: 369123239fc7
Create Date: 2023-06-15 08:50:15.876193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dadc39e1615'
down_revision = '369123239fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
