"""update db

Revision ID: 369123239fc7
Revises: 220c46c7811d
Create Date: 2023-06-14 10:07:33.246474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369123239fc7'
down_revision = '220c46c7811d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rental_history', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rental_history', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transaction_history', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transaction_history', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    op.drop_column('transaction_history', 'updatedAt')
    op.drop_column('transaction_history', 'createdAt')
    op.drop_column('rental_history', 'updatedAt')
    op.drop_column('rental_history', 'createdAt')
    op.drop_column('properties', 'updatedAt')
    op.drop_column('properties', 'createdAt')
    # ### end Alembic commands ###
