"""New Migration 1

Revision ID: 54662f344d42
Revises: 4e24424d62e1
Create Date: 2023-06-11 22:50:50.792548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54662f344d42'
down_revision = '4e24424d62e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
