"""create table

Revision ID: 5e0394f91517
Revises: f23a0b35bc92
Create Date: 2023-06-12 09:17:34.921179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0394f91517'
down_revision = 'f23a0b35bc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
