"""create table v3

Revision ID: 650035e7a17c
Revises: 1dadc39e1615
Create Date: 2023-06-15 08:58:26.529861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '650035e7a17c'
down_revision = '1dadc39e1615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('createdat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('updatedat', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('properties', 'updatedAt')
    op.drop_column('properties', 'createdAt')
    op.add_column('rental_history', sa.Column('createdat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rental_history', sa.Column('updatedat', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('rental_history', 'updatedAt')
    op.drop_column('rental_history', 'createdAt')
    op.add_column('transaction_history', sa.Column('createdat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transaction_history', sa.Column('updatedat', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('transaction_history', 'updatedAt')
    op.drop_column('transaction_history', 'createdAt')
    op.add_column('users', sa.Column('createdat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updatedat', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'updatedat')
    op.drop_column('users', 'createdat')
    op.add_column('transaction_history', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('transaction_history', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('transaction_history', 'updatedat')
    op.drop_column('transaction_history', 'createdat')
    op.add_column('rental_history', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('rental_history', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('rental_history', 'updatedat')
    op.drop_column('rental_history', 'createdat')
    op.add_column('properties', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('properties', 'updatedat')
    op.drop_column('properties', 'createdat')
    # ### end Alembic commands ###
