"""create table 4

Revision ID: 7d643f7e6556
Revises: cef734219a45
Create Date: 2023-06-12 09:44:22.271752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d643f7e6556'
down_revision = 'cef734219a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
