"""create table properties v2

Revision ID: 991c2cb2940e
Revises: b2f35098306c
Create Date: 2023-06-12 11:54:12.679940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991c2cb2940e'
down_revision = 'b2f35098306c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
