"""create table 1

Revision ID: c70bef9c20c9
Revises: 5e0394f91517
Create Date: 2023-06-12 09:27:55.659240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70bef9c20c9'
down_revision = '5e0394f91517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
