"""create table

Revision ID: f23a0b35bc92
Revises: 54662f344d42
Create Date: 2023-06-12 09:10:05.979120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23a0b35bc92'
down_revision = '54662f344d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
